// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return android;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2V0dpWJ1lKM_ASxoWOJ4DQPeZbsTX8LA',
    appId: '1:784022241138:android:bd181f72c77f3b8b28a7eb',
    messagingSenderId: '784022241138',
    projectId: 'flutex110',
    storageBucket: 'flutex110.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTb7F8OrQImV4kifA90xb8wJHvK7crTV4',
    appId: '1:784022241138:ios:00ec67455002321f28a7eb',
    messagingSenderId: '784022241138',
    projectId: 'flutex110',
    storageBucket: 'flutex110.firebasestorage.app',
    iosBundleId: 'com.flutex.admin',
  );

}